### ISSUE TITLE
No minimum python version listed, but 3.10 or above is required for `|` operator for union types.

### ISSUE THREAD

**Issue by Dtphelan1** [smart-on-fhir/chart-review#51]
Trying to install chart-review using Python 3.9 results in a TypeError that seems to be related to the [Python 3.10-added](https://peps.python.org/pep-0604/) pipe operator for defining union types. Screenshot provided below. 

Recommendation is _not_ at this point to support older Python versions, but just to clarify that 3.10 and up is needed in the documentation. Not sure where is best to provide that, if you point me in a location I can always make a PR if you're busy. 

<img width="993" alt="image" src="https://github.com/user-attachments/assets/2e3508ea-02f6-4232-8078-23fd8e229244">

**Comment by mikix** [comment]
Hmm, pyproject.toml lists minimum python as 3.9 - so if we broke that, it's probably a mistake

**Comment by mikix** [comment]
But our CI only tests on 3.10... probably should do all supported versions
